[graph]
all-features = true

[advisories]
unmaintained = "workspace"

[licenses]
confidence-threshold = 0.93
allow = [
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "CC0-1.0",
  "ISC",
  "LGPL-2.1-or-later",
  "MIT",
  "MPL-2.0",
  "Unicode-3.0",
  "Zlib",
]

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"

