use std::{
    collections::BTreeMap,
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
};

use helm_model::SettingValue;
use helm_transaction::{FileChange, Fingerprint, TransactionPlan};
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ConfigGeneration {
    Lua,
    LegacyReadOnly,
    Missing,
}

#[must_use]
pub fn detect_generation(directory: &Path) -> ConfigGeneration {
    if directory.join("hyprland.lua").is_file() {
        ConfigGeneration::Lua
    } else if directory.join("hyprland.conf").is_file() {
        ConfigGeneration::LegacyReadOnly
    } else {
        ConfigGeneration::Missing
    }
}

#[derive(Clone, Debug, Default)]
pub struct ManagedConfig {
    values: BTreeMap<String, SettingValue>,
    displays_lua: Option<String>,
    bindings_lua: Vec<String>,
}

impl ManagedConfig {
    pub fn set(&mut self, setting_id: impl Into<String>, value: SettingValue) {
        self.values.insert(setting_id.into(), value);
    }
    pub fn set_displays_lua(&mut self, lua: impl Into<String>) {
        self.displays_lua = Some(lua.into());
    }
    pub fn set_bindings_lua(&mut self, bindings: impl IntoIterator<Item = String>) {
        self.bindings_lua = bindings.into_iter().collect();
    }

    #[must_use]
    pub fn render(&self) -> String {
        let mut sections: BTreeMap<&str, Vec<(&str, &SettingValue)>> = BTreeMap::new();
        for (id, value) in &self.values {
            if let Some(path) = id.strip_prefix("hyprland.")
                && let Some((section, key)) = path.split_once('.')
            {
                sections.entry(section).or_default().push((key, value));
            }
        }
        let mut lua = String::from(
            "-- Generated by Helm. Manual changes will be replaced.\nlocal hl = require(\"hyprland\")\n\n",
        );
        for (section, values) in sections {
            writeln!(lua, "hl.config({{ {section} = {{").expect("writing to a String cannot fail");
            for (key, value) in values {
                writeln!(lua, "  {key} = {},", render_value(value))
                    .expect("writing to a String cannot fail");
            }
            lua.push_str("} })\n\n");
        }
        if let Some(displays) = &self.displays_lua {
            lua.push_str("-- Displays\n");
            lua.push_str(displays);
            lua.push('\n');
        }
        if !self.bindings_lua.is_empty() {
            lua.push_str("-- Keybindings\n");
            for binding in &self.bindings_lua {
                lua.push_str(binding);
                lua.push('\n');
            }
        }
        lua
    }
}

pub struct IntegrationPlan {
    pub plan: TransactionPlan,
    pub main_config: PathBuf,
    pub managed_module: PathBuf,
}

impl IntegrationPlan {
    pub fn create(directory: &Path, managed: &ManagedConfig) -> Result<Self, std::io::Error> {
        let main_config = directory.join("hyprland.lua");
        let managed_module = directory.join("helm-settings/init.lua");
        let current_main = fs::read(&main_config)?;
        let text = String::from_utf8_lossy(&current_main);
        let integration = "pcall(require, \"helm-settings.init\")";
        let new_main = if text.contains(integration) {
            current_main.clone()
        } else {
            let mut bytes = current_main.clone();
            if !bytes.ends_with(b"\n") {
                bytes.push(b'\n');
            }
            bytes.extend_from_slice(
                format!("\n-- Helm managed settings\n{integration}\n").as_bytes(),
            );
            bytes
        };
        let current_module = fs::read(&managed_module).ok();
        Ok(Self {
            plan: TransactionPlan {
                summary: "Integrate Helm with Hyprland".into(),
                changes: vec![
                    FileChange::write(
                        &main_config,
                        Some(Fingerprint::bytes(&current_main)),
                        new_main,
                    ),
                    FileChange::write(
                        &managed_module,
                        current_module.as_deref().map(Fingerprint::bytes),
                        managed.render().into_bytes(),
                    ),
                ],
            },
            main_config,
            managed_module,
        })
    }
}

fn render_value(value: &SettingValue) -> String {
    match value {
        SettingValue::Bool(value) => value.to_string(),
        SettingValue::Integer(value) => value.to_string(),
        SettingValue::Decimal(value) => value.to_string(),
        SettingValue::Text(value)
        | SettingValue::Choice(value)
        | SettingValue::Color(value)
        | SettingValue::Path(value) => format!("{value:?}"),
        SettingValue::List(_) | SettingValue::Object(_) | SettingValue::Unset => "nil".into(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn legacy_config_is_read_only() {
        let directory = tempfile::tempdir().expect("tempdir");
        fs::write(directory.path().join("hyprland.conf"), "legacy").expect("fixture");
        assert_eq!(
            detect_generation(directory.path()),
            ConfigGeneration::LegacyReadOnly
        );
    }
    #[test]
    fn integration_appends_one_guarded_import() {
        let directory = tempfile::tempdir().expect("tempdir");
        fs::write(
            directory.path().join("hyprland.lua"),
            "local hl = require(\"hyprland\")\n",
        )
        .expect("fixture");
        fs::create_dir(directory.path().join("helm-settings")).expect("module dir");
        let mut managed = ManagedConfig::default();
        managed.set("hyprland.general.border_size", SettingValue::Integer(2));
        let plan = IntegrationPlan::create(directory.path(), &managed).expect("plan");
        let replacement = plan.plan.changes[0]
            .replacement
            .as_deref()
            .expect("replacement");
        assert_eq!(
            String::from_utf8_lossy(replacement)
                .matches("helm-settings.init")
                .count(),
            1
        );
        assert!(managed.render().contains("border_size = 2"));
    }
}
