use std::{
    collections::{BTreeMap, BTreeSet},
    fmt::Write as _,
};

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Display {
    pub id: i64,
    pub name: String,
    pub description: String,
    pub make: String,
    pub model: String,
    pub serial: String,
    pub width: i64,
    pub height: i64,
    pub refresh_rate: f64,
    pub x: i64,
    pub y: i64,
    pub scale: f64,
    pub transform: i64,
    pub disabled: bool,
    pub mirror_of: String,
    pub available_modes: Vec<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DisplayLayout {
    pub outputs: Vec<DisplayTarget>,
    pub fallback: FallbackRule,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DisplayTarget {
    pub output: String,
    pub mode: String,
    pub x: i64,
    pub y: i64,
    pub scale: f64,
    pub transform: i64,
    pub disabled: bool,
    pub mirror: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FallbackRule {
    pub mode: String,
    pub position: String,
    pub scale: f64,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum DisplayValidation {
    Valid,
    NoUsableOutput,
    MirrorCycle,
    SelfMirror(String),
    InvalidScale(String),
    DuplicateOutput(String),
}

#[must_use]
pub fn validate_display_layout(layout: &DisplayLayout) -> DisplayValidation {
    let mut seen = BTreeSet::new();
    for output in &layout.outputs {
        if !seen.insert(&output.output) {
            return DisplayValidation::DuplicateOutput(output.output.clone());
        }
        if output.scale <= 0.0 || !output.scale.is_finite() {
            return DisplayValidation::InvalidScale(output.output.clone());
        }
        if output.mirror.as_deref() == Some(output.output.as_str()) {
            return DisplayValidation::SelfMirror(output.output.clone());
        }
    }
    if !layout
        .outputs
        .iter()
        .any(|output| !output.disabled && output.mirror.is_none())
    {
        return DisplayValidation::NoUsableOutput;
    }
    let mirrors = layout
        .outputs
        .iter()
        .filter_map(|output| {
            output
                .mirror
                .as_ref()
                .map(|target| (&output.output, target))
        })
        .collect::<BTreeMap<_, _>>();
    for start in mirrors.keys() {
        let mut current = *start;
        let mut path = BTreeSet::new();
        while let Some(next) = mirrors.get(current) {
            if !path.insert(current) {
                return DisplayValidation::MirrorCycle;
            }
            current = next;
        }
    }
    DisplayValidation::Valid
}

impl DisplayLayout {
    #[must_use]
    pub fn to_lua(&self) -> String {
        let mut lua = String::from(
            "-- Generated by Helm. Do not edit.\nlocal hl = require(\"hyprland\")\n\n",
        );
        for output in &self.outputs {
            write!(lua, "hl.monitor({{ output = {}, mode = {}, position = {{ {}, {} }}, scale = {}, transform = {}, disabled = {}", lua_string(&output.output), lua_string(&output.mode), output.x, output.y, output.scale, output.transform, output.disabled).expect("writing to a String cannot fail");
            if let Some(mirror) = &output.mirror {
                write!(lua, ", mirror = {}", lua_string(mirror))
                    .expect("writing to a String cannot fail");
            }
            lua.push_str(" })\n");
        }
        writeln!(
            lua,
            "hl.monitor({{ output = \"\", mode = {}, position = {}, scale = {} }})\n",
            lua_string(&self.fallback.mode),
            lua_string(&self.fallback.position),
            self.fallback.scale
        )
        .expect("writing to a String cannot fail");
        lua
    }
}

fn lua_string(value: &str) -> String {
    format!("{value:?}")
}

#[cfg(test)]
mod tests {
    use super::*;
    fn layout() -> DisplayLayout {
        DisplayLayout {
            outputs: vec![DisplayTarget {
                output: "eDP-1".into(),
                mode: "preferred".into(),
                x: 0,
                y: 0,
                scale: 2.0,
                transform: 0,
                disabled: false,
                mirror: None,
            }],
            fallback: FallbackRule {
                mode: "preferred".into(),
                position: "auto".into(),
                scale: 1.0,
            },
        }
    }
    #[test]
    fn valid_layout_has_root_and_fallback() {
        let layout = layout();
        assert_eq!(validate_display_layout(&layout), DisplayValidation::Valid);
        assert!(layout.to_lua().contains("output = \"\""));
    }
    #[test]
    fn rejects_last_output_disabled() {
        let mut layout = layout();
        layout.outputs[0].disabled = true;
        assert_eq!(
            validate_display_layout(&layout),
            DisplayValidation::NoUsableOutput
        );
    }
    #[test]
    fn rejects_mirror_cycle() {
        let mut layout = layout();
        layout.outputs.push(DisplayTarget {
            output: "HDMI-A-1".into(),
            mode: "preferred".into(),
            x: 0,
            y: 0,
            scale: 1.0,
            transform: 0,
            disabled: false,
            mirror: Some("DP-1".into()),
        });
        layout.outputs.push(DisplayTarget {
            output: "DP-1".into(),
            mode: "preferred".into(),
            x: 0,
            y: 0,
            scale: 1.0,
            transform: 0,
            disabled: false,
            mirror: Some("HDMI-A-1".into()),
        });
        assert_eq!(
            validate_display_layout(&layout),
            DisplayValidation::MirrorCycle
        );
    }
}
