[package]
name = "helm-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
clap.workspace = true
helm-core = { path = "../helm-core", version = "1.0.0" }
helm-adapter-applications = { path = "../../adapters/applications", version = "1.0.0" }
helm-adapter-bars = { path = "../../adapters/bars", version = "1.0.0" }
helm-adapter-desktop = { path = "../../adapters/desktop", version = "1.0.0" }
helm-adapter-hyprland = { path = "../../adapters/hyprland", version = "1.0.0" }
helm-transaction = { path = "../helm-transaction", version = "1.0.0" }
helm-plugin-host = { path = "../helm-plugin-host", version = "1.0.0" }
serde.workspace = true
serde_json.workspace = true
toml_edit.workspace = true

[lints]
workspace = true
