[package]
name = "helm-gui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
build = "build.rs"

[dependencies]
helm-core = { path = "../helm-core" }
helm-adapter-applications = { path = "../../adapters/applications" }
helm-adapter-bars = { path = "../../adapters/bars" }
helm-adapter-hyprland = { path = "../../adapters/hyprland" }
helm-transaction = { path = "../helm-transaction" }
helm-plugin-host = { path = "../helm-plugin-host" }
gtk.workspace = true
adw.workspace = true
glib.workspace = true

[build-dependencies]
glib-build-tools.workspace = true

[lints]
workspace = true
