[package]
name = "helm-gui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
build = "build.rs"

[dependencies]
helm-core = { path = "../helm-core", version = "0.9.0" }
helm-adapter-applications = { path = "../../adapters/applications", version = "0.9.0" }
helm-adapter-bars = { path = "../../adapters/bars", version = "0.9.0" }
helm-adapter-hyprland = { path = "../../adapters/hyprland", version = "0.9.0" }
helm-transaction = { path = "../helm-transaction", version = "0.9.0" }
helm-plugin-host = { path = "../helm-plugin-host", version = "0.9.0" }
gtk.workspace = true
adw.workspace = true
glib.workspace = true

[build-dependencies]
glib-build-tools.workspace = true

[lints]
workspace = true
