use std::fmt::Write as _;

use serde::{Deserialize, Serialize};

use crate::{Error, Result};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WindowRule {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub class: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub workspace: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub floating: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub opacity: Option<f64>,
}

impl WindowRule {
    pub fn validate(&self) -> Result<()> {
        if self.name.is_empty()
            || !self
                .name
                .bytes()
                .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_'))
        {
            return Err(Error::Invalid(format!("invalid rule name `{}`", self.name)));
        }
        if self.class.is_none() && self.title.is_none() {
            return Err(Error::Invalid(format!(
                "rule `{}` needs a class or title match",
                self.name
            )));
        }
        if self
            .opacity
            .is_some_and(|value| !(0.0..=1.0).contains(&value))
        {
            return Err(Error::Invalid(
                "rule opacity must be between 0 and 1".into(),
            ));
        }
        for value in self.class.iter().chain(&self.title).chain(&self.workspace) {
            if value.contains(['\n', '\r']) {
                return Err(Error::Invalid("rule fields cannot contain newlines".into()));
            }
        }
        Ok(())
    }
}

pub fn render(rules: &[WindowRule]) -> Result<String> {
    let mut output = String::from("-- Generated by Helm.\nlocal hl = require(\"hyprland\")\n\n");
    for rule in rules {
        rule.validate()?;
        writeln!(output, "hl.window_rule({{").expect("String write");
        writeln!(output, "  name = {:?},", rule.name).expect("String write");
        output.push_str("  match = {\n");
        if let Some(class) = &rule.class {
            writeln!(output, "    class = {class:?},").expect("String write");
        }
        if let Some(title) = &rule.title {
            writeln!(output, "    title = {title:?},").expect("String write");
        }
        output.push_str("  },\n");
        if let Some(workspace) = &rule.workspace {
            writeln!(output, "  workspace = {workspace:?},").expect("String write");
        }
        if let Some(floating) = rule.floating {
            writeln!(output, "  float = {floating},").expect("String write");
        }
        if let Some(opacity) = rule.opacity {
            writeln!(output, "  opacity = {:?},", format!("{opacity} override"))
                .expect("String write");
        }
        output.push_str("})\n\n");
    }
    Ok(output)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_named_lua_rule() {
        let result = render(&[WindowRule {
            name: "float-dialogs".into(),
            class: Some("org.example.App".into()),
            title: None,
            workspace: None,
            floating: Some(true),
            opacity: Some(0.9),
        }])
        .expect("render");
        assert!(result.contains("hl.window_rule"));
        assert!(result.contains("float = true"));
    }
}
