use std::{
    fmt::Write as _,
    path::{Path, PathBuf},
};

use serde::{Deserialize, Serialize};

use crate::{Error, Result};

#[derive(Clone, Copy, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum FitMode {
    Contain,
    #[default]
    Cover,
    Tile,
    Fill,
}

impl FitMode {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Contain => "contain",
            Self::Cover => "cover",
            Self::Tile => "tile",
            Self::Fill => "fill",
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct Wallpaper {
    #[serde(default)]
    pub monitor: String,
    pub path: PathBuf,
    #[serde(default)]
    pub fit: FitMode,
}

impl Wallpaper {
    pub fn validate(&self) -> Result<()> {
        if !self.path.is_absolute() {
            return Err(Error::Invalid("wallpaper path must be absolute".into()));
        }
        if self.path.to_string_lossy().contains(['\n', '\r']) || self.monitor.contains(['\n', '\r'])
        {
            return Err(Error::Invalid(
                "wallpaper fields cannot contain newlines".into(),
            ));
        }
        Ok(())
    }
}

pub fn render(wallpapers: &[Wallpaper]) -> Result<String> {
    if wallpapers.is_empty() {
        return Err(Error::Invalid(
            "a profile needs at least one wallpaper".into(),
        ));
    }
    let mut output = String::from("# Generated by Helm.\nipc = true\nsplash = false\n\n");
    for wallpaper in wallpapers {
        wallpaper.validate()?;
        writeln!(
            output,
            "wallpaper {{\n  monitor = {}\n  path = {}\n  fit_mode = {}\n}}\n",
            wallpaper.monitor,
            wallpaper.path.display(),
            wallpaper.fit.as_str()
        )
        .expect("writing to a String cannot fail");
    }
    Ok(output)
}

#[must_use]
pub fn integrate_source(source: &str, managed_path: &Path) -> String {
    let directive = format!("source = {}", managed_path.display());
    if source.lines().any(|line| line.trim() == directive) {
        return source.to_owned();
    }
    format!(
        "{}{separator}{directive}\n",
        source,
        separator = if source.is_empty() || source.ends_with('\n') {
            ""
        } else {
            "\n"
        }
    )
}

#[must_use]
pub fn managed_path(config_home: &Path) -> PathBuf {
    config_home.join("hypr/hyprpaper.d/helm-settings.conf")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_current_special_category_format() {
        let output = render(&[Wallpaper {
            monitor: "DP-1".into(),
            path: PathBuf::from("/wallpaper.jpg"),
            fit: FitMode::Cover,
        }])
        .expect("render");
        assert!(output.contains("wallpaper {"));
        assert!(output.contains("fit_mode = cover"));
    }

    #[test]
    fn adds_managed_source_once() {
        let first = integrate_source("splash = true\n", Path::new("/config/managed.conf"));
        let second = integrate_source(&first, Path::new("/config/managed.conf"));
        assert_eq!(second.matches("source =").count(), 1);
    }
}
