use std::path::{Path, PathBuf};

use helm_adapter_applications::theme::Theme;
use serde::Serialize;

use crate::{Layout, Position};

#[derive(Clone, Debug, Eq, PartialEq, Serialize)]
pub struct Status {
    pub root_shell: Option<PathBuf>,
    pub managed_shell: PathBuf,
    pub managed: bool,
    pub cooperative: bool,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Plan {
    pub shell_path: PathBuf,
    pub shell: String,
}

#[must_use]
pub fn detect(config_home: &Path) -> Status {
    let directory = config_home.join("quickshell");
    let root = directory.join("shell.qml");
    let managed_shell = directory.join("helm-settings/shell.qml");
    Status {
        root_shell: root.is_file().then_some(root),
        managed: managed_shell.is_file(),
        managed_shell,
        cooperative: true,
    }
}

pub fn plan(config_home: &Path, layout: &Layout, theme: &Theme) -> Result<Plan, String> {
    layout.validate()?;
    theme.validate().map_err(|error| error.to_string())?;
    let horizontal = matches!(layout.position, Position::Top | Position::Bottom);
    let anchor = layout.position.as_str();
    let modules = layout
        .left
        .iter()
        .chain(&layout.center)
        .chain(&layout.right)
        .map(|module| qml_string(module))
        .collect::<Vec<_>>()
        .join(", ");
    let shell = format!(
        "// Generated by Helm as a separate named Quickshell configuration.\nimport Quickshell\nimport QtQuick\n\nShellRoot {{\n  Variants {{\n    model: Quickshell.screens\n    PanelWindow {{\n      required property var modelData\n      screen: modelData\n      anchors {{ {anchor}: true; {}: true; {}: true }}\n      {}: {}\n      color: \"{}\"\n      Row {{\n        anchors.centerIn: parent\n        spacing: {}\n        Repeater {{\n          model: [{}]\n          Text {{ required property string modelData; text: modelData; color: \"{}\" }}\n        }}\n      }}\n    }}\n  }}\n}}\n",
        if horizontal { "left" } else { "top" },
        if horizontal { "right" } else { "bottom" },
        if horizontal {
            "implicitHeight"
        } else {
            "implicitWidth"
        },
        layout.size,
        theme.background,
        layout.spacing,
        modules,
        theme.foreground,
    );
    Ok(Plan {
        shell_path: config_home.join("quickshell/helm-settings/shell.qml"),
        shell,
    })
}

fn qml_string(value: &str) -> String {
    format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn never_overwrites_the_user_root_shell() {
        let theme = helm_adapter_applications::theme::builtins().remove(0);
        let plan = plan(Path::new("/config"), &Layout::default(), &theme).expect("plan");
        assert_eq!(
            plan.shell_path,
            Path::new("/config/quickshell/helm-settings/shell.qml")
        );
        assert!(plan.shell.contains("Variants"));
    }
}
