use std::path::{Path, PathBuf};

use helm_adapter_applications::theme::Theme;
use serde::Serialize;

use crate::Layout;

#[derive(Clone, Debug, Eq, PartialEq, Serialize)]
pub struct Status {
    pub user_config: Option<PathBuf>,
    pub managed_config: PathBuf,
    pub managed: bool,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Plan {
    pub config_path: PathBuf,
    pub config: String,
    pub style_path: PathBuf,
    pub style: String,
}

#[must_use]
pub fn detect(config_home: &Path) -> Status {
    let directory = config_home.join("waybar");
    let user_config = [directory.join("config"), directory.join("config.jsonc")]
        .into_iter()
        .find(|path| path.is_file());
    let managed_config = directory.join("helm-settings/config.jsonc");
    Status {
        managed: managed_config.is_file(),
        managed_config,
        user_config,
    }
}

pub fn plan(config_home: &Path, layout: &Layout, theme: &Theme) -> Result<Plan, String> {
    layout.validate()?;
    theme.validate().map_err(|error| error.to_string())?;
    let directory = config_home.join("waybar/helm-settings");
    let size_key = match layout.position {
        crate::Position::Left | crate::Position::Right => "width",
        crate::Position::Top | crate::Position::Bottom => "height",
    };
    let value = serde_json::json!({
        "layer": "top",
        "position": layout.position.as_str(),
        (size_key): layout.size,
        "spacing": layout.spacing,
        "reload_style_on_change": true,
        "modules-left": layout.left,
        "modules-center": layout.center,
        "modules-right": layout.right,
        "clock": { "format": "{:%H:%M}", "tooltip-format": "{:%A, %d %B %Y}" },
        "network": { "format-wifi": "{essid} {signalStrength}%", "format-disconnected": "offline" },
        "pulseaudio": { "format": "volume {volume}%", "format-muted": "muted" },
        "battery": { "format": "battery {capacity}%" },
    });
    let mut config = String::from("// Generated by Helm. Edit the Helm layout, not this file.\n");
    config.push_str(&serde_json::to_string_pretty(&value).map_err(|error| error.to_string())?);
    config.push('\n');
    let style = format!(
        "/* Generated by Helm. */\n* {{ font-family: sans-serif; font-size: 13px; }}\nwindow#waybar {{ background: {}; color: {}; }}\n#workspaces button.focused, #clock {{ color: {}; }}\n",
        theme.background, theme.foreground, theme.cursor
    );
    Ok(Plan {
        config_path: directory.join("config.jsonc"),
        config,
        style_path: directory.join("style.css"),
        style,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_standalone_jsonc_and_css() {
        let theme = helm_adapter_applications::theme::builtins().remove(0);
        let plan = plan(Path::new("/config"), &Layout::default(), &theme).expect("plan");
        let json = plan.config.lines().skip(1).collect::<Vec<_>>().join("\n");
        serde_json::from_str::<serde_json::Value>(&json).expect("valid JSON payload");
        assert!(plan.style.contains(&theme.background));
    }
}
