use std::{
    fmt::Write as _,
    path::{Path, PathBuf},
};

use serde::Serialize;
use toml_edit::{Array, DocumentMut, Item, Table, value};

use crate::{AdapterError, Result, theme::Theme};

pub const MANAGED_IMPORT: &str = "helm-settings/theme.toml";

#[derive(Clone, Debug, Eq, PartialEq, Serialize)]
pub enum ConfigState {
    Missing,
    Toml { path: PathBuf, managed: bool },
    LegacyYaml { path: PathBuf },
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ThemePlan {
    pub root_path: PathBuf,
    pub root_content: String,
    pub fragment_path: PathBuf,
    pub fragment_content: String,
}

#[must_use]
pub fn detect(config_home: &Path) -> ConfigState {
    let directory = config_home.join("alacritty");
    let toml = directory.join("alacritty.toml");
    if toml.is_file() {
        let managed =
            std::fs::read_to_string(&toml).is_ok_and(|text| text.contains(MANAGED_IMPORT));
        return ConfigState::Toml {
            path: toml,
            managed,
        };
    }
    let yaml = directory.join("alacritty.yml");
    if yaml.is_file() {
        return ConfigState::LegacyYaml { path: yaml };
    }
    ConfigState::Missing
}

pub fn plan_theme(config_home: &Path, root: &str, theme: &Theme) -> Result<ThemePlan> {
    theme.validate()?;
    let root_path = config_home.join("alacritty/alacritty.toml");
    let mut document = root.parse::<DocumentMut>()?;
    if document.get("general").is_none() {
        document["general"] = Item::Table(Table::new());
    }
    let general = document["general"]
        .as_table_mut()
        .ok_or_else(|| AdapterError::Unsupported("Alacritty `general` must be a table".into()))?;
    if general.get("import").is_none() {
        general["import"] = value(Array::new());
    }
    let imports = general["import"].as_array_mut().ok_or_else(|| {
        AdapterError::Unsupported("Alacritty `general.import` must be an array".into())
    })?;
    if !imports
        .iter()
        .any(|entry| entry.as_str() == Some(MANAGED_IMPORT))
    {
        imports.push(MANAGED_IMPORT);
    }
    Ok(ThemePlan {
        root_path,
        root_content: document.to_string(),
        fragment_path: config_home.join("alacritty").join(MANAGED_IMPORT),
        fragment_content: render_theme(theme),
    })
}

#[must_use]
pub fn render_theme(theme: &Theme) -> String {
    let mut output = format!(
        "# Generated by Helm. Edit the source theme, not this file.\n\n[colors.primary]\nbackground = \"{}\"\nforeground = \"{}\"\n\n[colors.cursor]\ncursor = \"{}\"\ntext = \"{}\"\n\n[colors.normal]\n",
        theme.background, theme.foreground, theme.cursor, theme.background
    );
    for name in crate::theme::ANSI_NAMES {
        writeln!(output, "{name} = \"{}\"", theme.normal[name])
            .expect("writing to a String cannot fail");
    }
    output.push_str("\n[colors.bright]\n");
    for name in crate::theme::ANSI_NAMES {
        writeln!(output, "{name} = \"{}\"", theme.bright[name])
            .expect("writing to a String cannot fail");
    }
    output
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn preserves_comments_and_adds_import_once() {
        let source = "# mine\n[window]\nopacity = 0.8\n";
        let theme = crate::theme::builtins().remove(0);
        let first = plan_theme(Path::new("/config"), source, &theme).expect("plan");
        let second = plan_theme(Path::new("/config"), &first.root_content, &theme).expect("plan");
        assert!(second.root_content.contains("# mine"));
        assert_eq!(second.root_content.matches(MANAGED_IMPORT).count(), 1);
        assert!(second.fragment_content.contains("[colors.normal]"));
    }
}
